// Generated by https://quicktype.io

class Menu {
  int idMenu;
  String codigoMenu;
  String nombreMenu;
  String descripcionMenu;
  String? rutaMenu;

  Menu({
    required this.idMenu,
    required this.codigoMenu,
    required this.nombreMenu,
    required this.descripcionMenu,
    required this.rutaMenu,
  });
}
