// Generated by https://quicktype.io

import 'package:fenix_app_v2/features/orders/domain/entities/activity.dart';
import 'package:fenix_app_v2/features/orders/domain/entities/client.dart';
import 'package:fenix_app_v2/features/orders/domain/entities/order_status.dart';

class Order {
  int idOrden;
  String numeroOrden;
  String direccion;
  String fechaProgramacion;
  int idEstadoOrden;
  int idCliente;
  int idActividad;
  Client cliente;
  OrderStatus estadoOrden;
  Activity actividad;

  Order(Map map, {
    required this.idOrden,
    required this.numeroOrden,
    required this.direccion,
    required this.fechaProgramacion,
    required this.idEstadoOrden,
    required this.idCliente,
    required this.idActividad,
    required this.cliente,
    required this.estadoOrden,
    required this.actividad,
  });

  Map<String, dynamic> toJson() => {
        "id_orden": idOrden,
        "numero_orden": numeroOrden,
        "direccion": direccion,
        "fecha_programacion": fechaProgramacion,
        "id_estado_orden": idEstadoOrden,
        "id_cliente": idCliente,
        "id_actividad": idActividad,
        "cliente": cliente.toJson(),
        "estado_orden": estadoOrden.toJson(),
        "actividad": actividad.toJson(),
      };
}
